fragment OrgAttributes on Org {
  _id
  name
  description
  createdAt
  status
  phones
  products {
    _id
    isPublic
    name
    description
    files {
      _id
      refType
      images{
        _id
        imgUrl
      }
    }
    updatedAt
    createdAt
  }
  files {
    _id
    refType
    images {
      _id
      imgUrl
    }
  }
}
