fragment ProductAttributes on Product {
  _id
  isPublic
  name
  description
  name
  description
  price
  countView
  countMember
  countTrxQty
  countReview
  countTrxAmount
  locations {
    _id
    address
    city
    zipcode
    owner {
        fullname
    }
    latitude
    longitude
    province
 }
  tags {
   _id
   name
   description
   files {
     _id
     type
     url
   }
 }
 files {
   _id
   type
   url
 }
 owner {
   _id
   type
   fullname
   url
 }
  # updatedAt
  # createdAt
}
