fragment ProductAttributes on Product {
  _id
  isPublic
  name
  description
  name
  description
  price
  viewCount
  orderCount
  locations {
    _id
    address
    city
    postcode
    orgId
    latitude
    longitude
    province
  }
  categories {
    _id
    name
    description
    files {
      _id
      refId
      fileUrl
      images {
        _id
        imgUrl
      }
    }
  }
  files {
    _id
    refType
    images{
      _id
      imgUrl
    }
  }
  user {
    _id
    name {
      first
      last
    }
    files {
      _id
      images {
        _id
        imgUrl
      }
    }
    org {
      _id
    }
  }
  updatedAt
  createdAt
}
