#import "../fragments/Org.gql"

query orgs {
  orgs {
    _id
    name
    description
    createdAt
    status
    phones
    products {
      _id
      isPublic
      name
      description
      files {
        _id
        type
        images{
          _id
          imgUrl
        }
      }
      updatedAt
      createdAt
    }
    files {
      _id
      type
      images {
        _id
        imgUrl
      }
    }
  }
}

query org($_id: String) {
  org(_id: $_id) {
    ...OrgAttributes
  }
}

query editOrg($_id: String) {
  org(_id: $_id) {
    ...OrgAttributes
  }
}
