#import "../fragments/Products.gql"

query products {
  products {
    _id
    isPublic
    name
    description
    files {
      _id
      type
      images{
        _id
        imgUrl
      }
    }
    updatedAt
    createdAt
  }
}

query product($_id: String) {
  product(_id: $_id) {
    ...ProductAttributes
  }
}

query editProduct($_id: String) {
  product(_id: $_id) {
    ...ProductAttributes
  }
}
