#import "../fragments/Product.gql"

query products {
    products {
       _id
       isPublic
       name
       description
       countView
       countMember
       countTrxQty
       countReview
       countTrxAmount
       price
       locations {
         _id
         address
         city
         zipcode
         owner {
           fullname
         }
         latitude
         longitude
         province
       }
       tags {
         _id
         name
         description
         files {
           _id
           type
           url
         }
       }
       # reviews {
       #   _id
       #   review
       #   productId
       #   createdAt
       #   user {
       #     _id
       #     name {
       #       first
       #       last
       #     }
       #   }
       # }
       files {
         _id
         type
         url
       }
       owner {
         _id
         type
         fullname
         url
       }
       # user {
       #   _id
       #   name {
       #     first
       #     last
       #   }
       #   files {
       #     _id
       #     images {
       #       _id
       #       imgUrl
       #     }
       #   }
       #   org {
       #     _id
       #   }
       # }
       # updatedAt
       # createdAt
     }
}

query product($_id: String) {
  product(_id: $_id) {
    ...ProductAttributes
  }
}

query editProduct($_id: String) {
  product(_id: $_id) {
    ...ProductAttributes
  }
}
