#import "../fragments/Products.gql"

query products {
  products {
    _id
    isPublic
    name
    description
    updatedAt
    createdAt
  }
}

query editProduct($_id: String) {
  product(_id: $_id) {
    ...ProductAttributes
  }
}

query product($_id: String) {
  product(_id: $_id) {
    ...ProductAttributes
    comments {
      _id
      comment
      createdAt
      user {
        _id
        name {
          first
          last
        }
      }
    }
  }
}
